### ISSUE TITLE
Support for Authentication?

### ISSUE THREAD

**Issue by joaquimadraz** [bbalser/elsa#61]
Hi there 👋 
Does `Elsa` support authentication? I would guess it does since it's using `brod`, but I can't figure out how to pass the authentication configs to `brod` - https://github.com/klarna/brod/wiki/SASL-gssapi-(kerberos)-authentication
Can I get some help with that? I'm happy to open a PR to update the docs after this 👍 

Thank you!

**Comment by joaquimadraz** [comment]
Here's what I have tried after checking `brod`'s code:

```elixir
Elsa.Supervisor.start_link(
  endpoints: [{"localhost", 9092}],
  config: [
    sasl: {:plain, "username",  "password"}
  ],
  connection: :my_producer,
  producer: [topic: "some.topic"]
)
```

Still wasn't able to connect.

**Comment by jeffgrunewald** [comment]
hey @joaquimadraz, thanks for your question!

are you able to share a little more with me about your configuration on the kafka side?

just following a setup i was able to find on a github issue elsewhere related to authentication against a dockerized kafka, i was able to successfully start both a producer and a group_consumer against a single-node dockerized cluster with plain sasl authentication and produce to/read from the topic with an authenticated connection (unauthenticated requests produced a `{:error, cluster_down}` tuple)

aside from the username and password, this configuration worked for me:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    links:
      - zookeeper
```
```
KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin-secret"
  user_admin="admin-secret"
  user_alice="alice-secret";
};
Client {};
```

the issue where i found the configuration is here for reference: https://github.com/wurstmeister/kafka-docker/issues/532
